amcl:
  ros__parameters:
    alpha1: 0.2
    alpha2: 0.2
    alpha3: 0.2
    alpha4: 0.2
    alpha5: 0.2
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false # Keep false unless you profile and find it necessary
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: 70.0 # Matches LiDAR
    laser_min_range: 1.0  # Matches LiDAR
    laser_model_type: "likelihood_field"
    max_beams: 360 # Increased from 70. Consider 180, 360, or 720 based on CPU.
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "nav2_amcl::DifferentialMotionModel"
    save_pose_rate: 0.5
    sigma_hit: 0.2 # Default, generally good. Can be tuned if map is very good.
    tf_broadcast: true
    transform_tolerance: 1.0 # Increased slightly, can be helpful with sim time issues or loaded systems
    update_min_a: 0.2
    update_min_d: 0.25
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    scan_topic: scan      # Matches LiDAR
    map_topic: map
    set_initial_pose: true
    always_reset_initial_pose: false
    first_map_only: false
    initial_pose:
      x: 100.72
      y: 5.53
      z: 0.0
      yaw: -2.90
    use_sim_time: True